apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: instana-agent-operator
spec:
  channel: stable
  name: instana-agent-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  config:
    resources:
      limits:
        memory: 512Mi
