apiVersion: instana.io/v1
kind: InstanaAgent
metadata:
  name: instana-agent
  namespace: instana-agent
spec:
  zone:
    name: <your-zone-name>
  cluster:
    name: <your-cluster-name>
  agent:
    keysSecret: instana-agent-key
    endpointHost: ingress-orange-saas.instana.io # the monitoring ingress endpoint
    endpointPort: "443" # the monitoring ingress endpoint port, wrapped in quotes
    env:
      INSTANA_AGENT_TAGS: <your-tags>
    configuration_yaml: |
      com.instana.plugin.ibmmq:
        enabled: true
        poll_rate: 60
        queueManagers:
          SINGLEINSTANCEQM:
            channel: 'SICHL'
            availabilityZone: 'IBM MQ'
          NATIVEHAQM:
            channel: 'METRICS'
            availabilityZone: 'IBM MQ'
