apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: empty-credentials
spec:
  type: barauth
  description: Empty username and password
  secretName: empty-credentials-secret
---
kind: Secret
apiVersion: v1
metadata:
  name: empty-credentials-secret
stringData:
  configuration: | 
    {"authType":"BASIC_AUTH","credentials":{"username":"","password":""}}
type: Opaque