apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: minimal-prod
spec:
  strimziOverrides:
    kafka:
      storage:
        class: ibmc-vpc-block-10iops-tier
    zookeeper:
      storage:
        class: ibmc-vpc-block-10iops-tier