apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cp4i-operators
spec:
  generators:
    - list:
      elements:
        - name: openshift-cert-manager
          namespace: cert-manager-operator
        - name: platformnavigator
          namespace: cp4i
        - name: mq
          namespace: cp4i
        - name: cert-utils
          namespace: cert-utils-operator       
        - name: clusterresourceoverride
          namespace: cp4i
       template:
    metadata:
      name: '{{name}}-operator'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: "100"
    spec:
      project: cp4i-operators
      source:
        path: 'components/{{name}}/operator'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
