kind: Secret
apiVersion: v1
metadata:
  name: mqwebuser-secret
type: Opaque
stringData:
  mqwebuser.xml: >-
    <?xml version="1.0" encoding="UTF-8"?>
    <server>

        <!--variable name="traceSpec" value="*=config"/-->      
        <basicRegistry id="basic" realm="defaultRealm">
            <user name="admin" password="<your-password>" />
      </basicRegistry>

        <enterpriseApplication id="com.ibm.mq.console" >
            <application-bnd>
                <security-role name="MQWebAdmin">
                    <user name="admin" realm="defaultRealm"/>
                </security-role>     
            </application-bnd>
        </enterpriseApplication>

    </server>