apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  name: scram-user
  labels:
    eventstreams.ibm.com/cluster: minimal-prod
    backup.eventstreams.ibm.com/component: kafkauser
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations:
          - Write
          - Create
          - Read
      - resource:
          type: topic
          name: __schema_
          patternType: prefix
        operations:
          - Read
          - Alter