kind: Secret
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: ibm-event-processing-ibm-ep-user-roles
type: Opaque
stringData:
  user-mapping.json: >-
    {
      "mappings": [
        {
          "id": "user1",
          "roles": [
            "user"
          ]
        }, 
        {
          "id": "user2",
          "roles": [
            "user"
          ]
        }
      ]
    }