kind: Secret
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: ibm-event-processing-ibm-ep-user-credentials
type: Opaque
stringData:
  user-credentials.json: >-
    {
      "users": [
          {
            "username": "user1",
            "password": "Password1$"
          },
          {
            "username": "user2",
            "password": "Password2$"
          }
      ]
    }

