kind: MessagingQueue
apiVersion: integration.ibm.com/v1beta1
metadata:
  name: queue-c
spec:
  messagingServer:
    name: sample-messagingserver
  queue:
    type: Local
    name: QUEUEC
    defaultPersistence: true
