apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mq-client-certificate-tls
spec:
  secretTemplate:
    annotations:
      cert-utils-operator.redhat-cop.io/generate-cert-info: "true"
      cert-utils-operator.redhat-cop.io/generate-java-keystores: "true"
  secretName: mq-client-certificate-tls-secret
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  commonName: "mqclient1"
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - key encipherment
    - digital signature
    - client auth
    - server auth
  issuerRef:
    name: mq-selfsigned-issuer