kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: haqmchl-route
spec:
  host: haqmchl.chl.mq.ibm.com
  to:
    kind: Service
    name: wellknown-cert-qm-ibm-mq
    weight: 100
  port:
    targetPort: qmgr
  tls:
    termination: passthrough
  wildcardPolicy: None